import ReactMarkdown from "react-markdown";

function RecommendationCard({ content }) {

  // Convert plain URLs into markdown links
  const formattedContent = (content || "").replace(
    /(https?:\/\/[^\s]+)/g,
    "[$1]($1)"
  );

  return (
    <div className="bg-white rounded-3xl shadow-xl border border-gray-200 p-8 mt-6">

      <div className="flex items-center gap-3 mb-6">
        <div className="text-4xl">🤖</div>

        <div>
          <h2 className="text-3xl font-bold text-blue-700">
            AI Scholarship Recommendations
          </h2>

          <p className="text-gray-500">
            Personalized recommendations generated by Google Gemini AI
          </p>
        </div>
      </div>

      <div className="prose prose-lg max-w-none bg-blue-50 rounded-2xl p-8 border border-blue-100">

        <ReactMarkdown
          components={{
            h1: ({ children }) => (
              <h1 className="text-3xl font-bold text-blue-700 mt-8 mb-4 border-b-2 border-blue-300 pb-3">
                🎓 {children}
              </h1>
            ),

            h2: ({ children }) => (
              <h2 className="text-xl font-bold text-indigo-700 mt-6 mb-3">
                {children}
              </h2>
            ),

            ul: ({ children }) => (
              <ul className="list-disc pl-6 space-y-2">
                {children}
              </ul>
            ),

            li: ({ children }) => (
              <li className="text-gray-700 leading-7">
                {children}
              </li>
            ),

            a: ({ href, children }) => (
              <a
                href={href}
                target="_blank"
                rel="noopener noreferrer"
                className="inline-flex items-center gap-2 text-blue-700 font-semibold underline hover:text-blue-900"
              >
                🌐 {children}
              </a>
            ),

            p: ({ children }) => (
              <p className="text-gray-700 leading-8">
                {children}
              </p>
            ),
          }}
        >
          {formattedContent}
        </ReactMarkdown>

      </div>

    </div>
  );
}

export default RecommendationCard;