import ReactMarkdown from "react-markdown";

function RecommendationCard({ content }) {
  const formattedContent = (content || "").replace(
    /(https?:\/\/[^\s]+)/g,
    "[$1]($1)"
  );

  return (
    <div className="w-full bg-white rounded-3xl shadow-xl border border-gray-200 p-4 sm:p-6 md:p-8 mt-6">

      {/* Header */}
      <div className="flex flex-col sm:flex-row items-start sm:items-center gap-4 mb-6">

        <div className="text-4xl sm:text-5xl">
          🤖
        </div>

        <div>
          <h2 className="text-2xl sm:text-3xl font-bold text-blue-700">
            AI Scholarship Recommendations
          </h2>

          <p className="text-gray-500 text-sm sm:text-base mt-1">
            Personalized recommendations generated by Google Gemini AI
          </p>
        </div>

      </div>

      {/* Recommendation Content */}
      <div className="prose max-w-none bg-blue-50 rounded-2xl p-4 sm:p-6 md:p-8 border border-blue-100 overflow-hidden">

        <ReactMarkdown
          components={{
            h1: ({ children }) => (
              <h1 className="text-2xl sm:text-3xl md:text-4xl font-bold text-blue-700 mt-8 mb-5 border-b-2 border-blue-300 pb-3 leading-tight break-words">
                🎓 {children}
              </h1>
            ),

            h2: ({ children }) => (
              <h2 className="text-xl sm:text-2xl font-bold text-indigo-700 mt-6 mb-3 leading-snug break-words">
                {children}
              </h2>
            ),

            h3: ({ children }) => (
              <h3 className="text-lg sm:text-xl font-semibold text-blue-700 mt-5 mb-3">
                {children}
              </h3>
            ),

            ul: ({ children }) => (
              <ul className="list-disc pl-5 space-y-2">
                {children}
              </ul>
            ),

            li: ({ children }) => (
              <li className="text-gray-700 text-sm sm:text-base leading-7 break-words">
                {children}
              </li>
            ),

            p: ({ children }) => (
              <p className="text-gray-700 text-sm sm:text-base leading-7 break-words">
                {children}
              </p>
            ),

            a: ({ href, children }) => (
              <a
                href={href}
                target="_blank"
                rel="noopener noreferrer"
                className="inline-flex items-center gap-2 text-blue-700 font-semibold underline hover:text-blue-900 break-all text-sm sm:text-base"
              >
                🌐 {children}
              </a>
            ),

            strong: ({ children }) => (
              <strong className="font-bold text-gray-900">
                {children}
              </strong>
            ),

            hr: () => (
              <hr className="my-8 border-blue-200" />
            ),
          }}
        >
          {formattedContent}
        </ReactMarkdown>

      </div>

    </div>
  );
}

export default RecommendationCard;